const resultado = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2064",
          "16",
          "Leão"
        ],
        [
          "2º",
          "8373",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "9287",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "2261",
          "16",
          "Leão"
        ],
        [
          "5º",
          "2803",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "5425",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "6726",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "9598",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "6409",
          "03",
          "Burro"
        ],
        [
          "10º",
          "6265",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9618",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "5080",
          "20",
          "Peru"
        ],
        [
          "3º",
          "3203",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "5229",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "1723",
          "06",
          "Cabra"
        ],
        [
          "6º",
          "5765",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "7902",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "1236",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "7933",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "0348",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6237",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "2349",
          "13",
          "Galo"
        ],
        [
          "3º",
          "5366",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "4673",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "2004",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "1737",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "1195",
          "24",
          "Veado"
        ],
        [
          "8º",
          "8824",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "9434",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "4817",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "19h - MALUCA - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0491",
          "23",
          "Urso"
        ],
        [
          "2º",
          "1351",
          "13",
          "Galo"
        ],
        [
          "3º",
          "7822",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "4219",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "8911",
          "03",
          "Burro"
        ],
        [
          "6º",
          "3119",
          "05",
          "Cachorro"
        ],
        [
          "7º",
          "2593",
          "24",
          "Veado"
        ],
        [
          "8º",
          "3531",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "4084",
          "21",
          "Touro"
        ],
        [
          "10º",
          "2047",
          "12",
          "Elefante"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2982",
          "21",
          "Touro"
        ],
        [
          "2º",
          "2230",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "6876",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "1734",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "3082",
          "21",
          "Touro"
        ],
        [
          "6º",
          "6965",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "4574",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "0922",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "9865",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "5626",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5359",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "2206",
          "02",
          "Águia"
        ],
        [
          "3º",
          "2081",
          "21",
          "Touro"
        ],
        [
          "4º",
          "9308",
          "02",
          "Águia"
        ],
        [
          "5º",
          "3271",
          "18",
          "Porco"
        ],
        [
          "6º",
          "7175",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "9297",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "3306",
          "02",
          "Águia"
        ],
        [
          "9º",
          "3625",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "8430",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "15h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4526",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "6332",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "7643",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "3697",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "4002",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "9811",
          "03",
          "Burro"
        ],
        [
          "7º",
          "4817",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "3293",
          "24",
          "Veado"
        ],
        [
          "9º",
          "4457",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "7184",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "19h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4710",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2834",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "1259",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "9211",
          "03",
          "Burro"
        ],
        [
          "5º",
          "1198",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "4323",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "0551",
          "13",
          "Galo"
        ],
        [
          "8º",
          "8391",
          "23",
          "Urso"
        ],
        [
          "9º",
          "4139",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "7402",
          "01",
          "Avestruz"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7695",
          "24",
          "Veado"
        ],
        [
          "2º",
          "8435",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "7792",
          "23",
          "Urso"
        ],
        [
          "4º",
          "0148",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "5088",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "7950",
          "13",
          "Galo"
        ],
        [
          "7º",
          "9502",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "9577",
          "20",
          "Peru"
        ],
        [
          "9º",
          "1213",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "4675",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1794",
          "24",
          "Veado"
        ],
        [
          "2º",
          "4067",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "8971",
          "18",
          "Porco"
        ],
        [
          "4º",
          "2817",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "1268",
          "17",
          "Macaco"
        ],
        [
          "6º",
          "3674",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "0916",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "3963",
          "16",
          "Leão"
        ],
        [
          "9º",
          "3874",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "3975",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 15:45 (tarde II)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9533",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "8925",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "6188",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "0901",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "2393",
          "24",
          "Veado"
        ],
        [
          "6º",
          "1086",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "0302",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "5355",
          "14",
          "Gato"
        ],
        [
          "9º",
          "4996",
          "24",
          "Veado"
        ],
        [
          "10º",
          "1040",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 19:00 (noite)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2632",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "9179",
          "20",
          "Peru"
        ],
        [
          "3º",
          "5701",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "9580",
          "20",
          "Peru"
        ],
        [
          "5º",
          "6036",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "4987",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "5613",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "6617",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "1912",
          "03",
          "Burro"
        ],
        [
          "10º",
          "2655",
          "14",
          "Gato"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2349",
          "13",
          "Galo"
        ],
        [
          "2º",
          "6321",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "9363",
          "16",
          "Leão"
        ],
        [
          "4º",
          "4983",
          "21",
          "Touro"
        ],
        [
          "5º",
          "7287",
          "22",
          "Tigre"
        ],
        [
          "6º [soma]",
          "0303",
          "",
          ""
        ],
        [
          "7º [mult]",
          "848",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2349",
          "13",
          "Galo"
        ],
        [
          "2º",
          "6321",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "9363",
          "16",
          "Leão"
        ],
        [
          "4º",
          "4983",
          "21",
          "Touro"
        ],
        [
          "5º",
          "7287",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "2694",
          "24",
          "Veado"
        ],
        [
          "7º",
          "3339",
          "10",
          "Coelho"
        ],
        [
          "8º",
          "4268",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "9133",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "9737",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2110",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2093",
          "24",
          "Veado"
        ],
        [
          "3º",
          "6939",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "0266",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "2294",
          "24",
          "Veado"
        ],
        [
          "6º [soma]",
          "3702",
          "",
          ""
        ],
        [
          "7º [mult]",
          "416",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2110",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2093",
          "24",
          "Veado"
        ],
        [
          "3º",
          "6939",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "0266",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "2294",
          "24",
          "Veado"
        ],
        [
          "6º",
          "2260",
          "15",
          "Jacaré"
        ],
        [
          "7º",
          "1092",
          "23",
          "Urso"
        ],
        [
          "8º",
          "1936",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "0396",
          "24",
          "Veado"
        ],
        [
          "10º",
          "9386",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2807",
          "02",
          "Águia"
        ],
        [
          "2º",
          "6988",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "9096",
          "24",
          "Veado"
        ],
        [
          "4º",
          "3651",
          "13",
          "Galo"
        ],
        [
          "5º",
          "6401",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "8943",
          "",
          ""
        ],
        [
          "7º [mult]",
          "615",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2807",
          "02",
          "Águia"
        ],
        [
          "2º",
          "6988",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "9096",
          "24",
          "Veado"
        ],
        [
          "4º",
          "3651",
          "13",
          "Galo"
        ],
        [
          "5º",
          "6401",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "2693",
          "24",
          "Veado"
        ],
        [
          "7º",
          "8906",
          "02",
          "Águia"
        ],
        [
          "8º",
          "0895",
          "24",
          "Veado"
        ],
        [
          "9º",
          "7861",
          "16",
          "Leão"
        ],
        [
          "10º",
          "9298",
          "25",
          "Vaca"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2499",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "9390",
          "23",
          "Urso"
        ],
        [
          "3º",
          "9434",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "6786",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "3030",
          "08",
          "Camelo"
        ],
        [
          "6º [soma]",
          "1139",
          "",
          ""
        ],
        [
          "7º [mult]",
          "465",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2499",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "9390",
          "23",
          "Urso"
        ],
        [
          "3º",
          "9434",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "6786",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "3030",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "2996",
          "24",
          "Veado"
        ],
        [
          "7º",
          "4347",
          "12",
          "Elefante"
        ],
        [
          "8º",
          "9938",
          "10",
          "Coelho"
        ],
        [
          "9º",
          "9046",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "7466",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7165",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "0397",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "3523",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "1773",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "8943",
          "11",
          "Cavalo"
        ],
        [
          "6º [soma]",
          "1801",
          "",
          ""
        ],
        [
          "7º [mult]",
          "844",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7165",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "0397",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "3523",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "1773",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "8943",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "7031",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "1357",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "6927",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "5733",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "2849",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3444",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "3284",
          "21",
          "Touro"
        ],
        [
          "3º",
          "6890",
          "23",
          "Urso"
        ],
        [
          "4º",
          "3939",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "8890",
          "23",
          "Urso"
        ],
        [
          "6º [soma]",
          "6447",
          "",
          ""
        ],
        [
          "7º [mult]",
          "310",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3444",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "3284",
          "21",
          "Touro"
        ],
        [
          "3º",
          "6890",
          "23",
          "Urso"
        ],
        [
          "4º",
          "3939",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "8890",
          "23",
          "Urso"
        ],
        [
          "6º",
          "3363",
          "16",
          "Leão"
        ],
        [
          "7º",
          "4289",
          "23",
          "Urso"
        ],
        [
          "8º",
          "4893",
          "24",
          "Veado"
        ],
        [
          "9º",
          "4409",
          "03",
          "Burro"
        ],
        [
          "10º",
          "3401",
          "01",
          "Avestruz"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1627",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "2926",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "1830",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "1677",
          "20",
          "Peru"
        ],
        [
          "5º",
          "8476",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "1211",
          "03",
          "Burro"
        ],
        [
          "7º",
          "6986",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "2237",
          "10",
          "Coelho"
        ],
        [
          "9º",
          "7607",
          "02",
          "Águia"
        ],
        [
          "10º",
          "4577",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3213",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "6845",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "2001",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "2359",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "8950",
          "13",
          "Galo"
        ],
        [
          "6º",
          "3622",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "2803",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "1405",
          "02",
          "Águia"
        ],
        [
          "9º",
          "3519",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "4717",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8537",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "0670",
          "18",
          "Porco"
        ],
        [
          "3º",
          "8035",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "1763",
          "16",
          "Leão"
        ],
        [
          "5º",
          "3011",
          "03",
          "Burro"
        ],
        [
          "6º",
          "8081",
          "21",
          "Touro"
        ],
        [
          "7º",
          "5607",
          "02",
          "Águia"
        ],
        [
          "8º",
          "3736",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "7053",
          "14",
          "Gato"
        ],
        [
          "10º",
          "6493",
          "24",
          "Veado"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 15:45h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5929",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "2324",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "0533",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "8344",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4218",
          "05",
          "Cachorro"
        ],
        [
          "6º",
          "5208",
          "02",
          "Águia"
        ],
        [
          "7º",
          "9353",
          "14",
          "Gato"
        ],
        [
          "8º",
          "2234",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "9434",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "7577",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 18h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4051",
          "13",
          "Galo"
        ],
        [
          "2º",
          "5275",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "8812",
          "03",
          "Burro"
        ],
        [
          "4º",
          "1748",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "4100",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "4581",
          "21",
          "Touro"
        ],
        [
          "7º",
          "0287",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "5714",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "1528",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "6096",
          "24",
          "Veado"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6108",
          "02",
          "Águia"
        ],
        [
          "2º",
          "0128",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "7202",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "7696",
          "24",
          "Veado"
        ],
        [
          "5º",
          "0908",
          "02",
          "Águia"
        ],
        [
          "6º [soma]",
          "2042",
          "",
          ""
        ],
        [
          "7º [mult]",
          "781",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6108",
          "02",
          "Águia"
        ],
        [
          "2º",
          "0128",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "7202",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "7696",
          "24",
          "Veado"
        ],
        [
          "5º",
          "0908",
          "02",
          "Águia"
        ],
        [
          "6º",
          "6077",
          "20",
          "Peru"
        ],
        [
          "7º",
          "1126",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "0209",
          "03",
          "Burro"
        ],
        [
          "9º",
          "8826",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "8280",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8465",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "7750",
          "13",
          "Galo"
        ],
        [
          "3º",
          "6811",
          "03",
          "Burro"
        ],
        [
          "4º",
          "1602",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "2539",
          "10",
          "Coelho"
        ],
        [
          "6º [soma]",
          "7167",
          "",
          ""
        ],
        [
          "7º [mult]",
          "603",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8465",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "7750",
          "13",
          "Galo"
        ],
        [
          "3º",
          "6811",
          "03",
          "Burro"
        ],
        [
          "4º",
          "1602",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "2539",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "8761",
          "16",
          "Leão"
        ],
        [
          "7º",
          "4786",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "6510",
          "03",
          "Burro"
        ],
        [
          "9º",
          "5012",
          "03",
          "Burro"
        ],
        [
          "10º",
          "2236",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7147",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "9354",
          "14",
          "Gato"
        ],
        [
          "3º",
          "1080",
          "20",
          "Peru"
        ],
        [
          "4º",
          "4436",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "1775",
          "19",
          "Pavão"
        ],
        [
          "6º [soma]",
          "3792",
          "",
          ""
        ],
        [
          "7º [mult]",
          "853",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7147",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "9354",
          "14",
          "Gato"
        ],
        [
          "3º",
          "1080",
          "20",
          "Peru"
        ],
        [
          "4º",
          "4436",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "1775",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "7914",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "1304",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "4583",
          "21",
          "Touro"
        ],
        [
          "9º",
          "7406",
          "02",
          "Águia"
        ],
        [
          "10º",
          "4999",
          "25",
          "Vaca"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5432",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "6711",
          "03",
          "Burro"
        ],
        [
          "3º",
          "1204",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "4107",
          "02",
          "Águia"
        ],
        [
          "5º",
          "7534",
          "09",
          "Cobra"
        ],
        [
          "6º [soma]",
          "4988",
          "",
          ""
        ],
        [
          "7º [mult]",
          "454",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5432",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "6711",
          "03",
          "Burro"
        ],
        [
          "3º",
          "1204",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "4107",
          "02",
          "Águia"
        ],
        [
          "5º",
          "7534",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "5614",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "4721",
          "06",
          "Cabra"
        ],
        [
          "8º",
          "3100",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "2147",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "0570",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3096",
          "24",
          "Veado"
        ],
        [
          "2º",
          "3549",
          "13",
          "Galo"
        ],
        [
          "3º",
          "3789",
          "23",
          "Urso"
        ],
        [
          "4º",
          "6122",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "7803",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "4359",
          "",
          ""
        ],
        [
          "7º [mult]",
          "987",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3096",
          "24",
          "Veado"
        ],
        [
          "2º",
          "3549",
          "13",
          "Galo"
        ],
        [
          "3º",
          "3789",
          "23",
          "Urso"
        ],
        [
          "4º",
          "6122",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "7803",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "3336",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "0571",
          "18",
          "Porco"
        ],
        [
          "8º",
          "9482",
          "21",
          "Touro"
        ],
        [
          "9º",
          "6992",
          "23",
          "Urso"
        ],
        [
          "10º",
          "4740",
          "10",
          "Coelho"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2014",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "9510",
          "03",
          "Burro"
        ],
        [
          "3º",
          "3713",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "8664",
          "16",
          "Leão"
        ],
        [
          "5º",
          "0108",
          "02",
          "Águia"
        ],
        [
          "6º [soma]",
          "4009",
          "",
          ""
        ],
        [
          "7º [mult]",
          "153",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2014",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "9510",
          "03",
          "Burro"
        ],
        [
          "3º",
          "3713",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "8664",
          "16",
          "Leão"
        ],
        [
          "5º",
          "0108",
          "02",
          "Águia"
        ],
        [
          "6º",
          "2938",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "0576",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "1116",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "4034",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "2673",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6213",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "5427",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "0688",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "2009",
          "03",
          "Burro"
        ],
        [
          "5º",
          "7402",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "1739",
          "",
          ""
        ],
        [
          "7º [mult]",
          "717",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6213",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "5427",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "0688",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "2009",
          "03",
          "Burro"
        ],
        [
          "5º",
          "7402",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "6502",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "2460",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "1280",
          "20",
          "Peru"
        ],
        [
          "9º",
          "3789",
          "23",
          "Urso"
        ],
        [
          "10º",
          "5770",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 12:00 - PTSP",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2555",
          "14",
          "Gato"
        ],
        [
          "2º",
          "9968",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "2413",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "1870",
          "18",
          "Porco"
        ],
        [
          "5º",
          "9506",
          "02",
          "Águia"
        ],
        [
          "6º [soma]",
          "6312",
          "",
          ""
        ],
        [
          "7º [mult]",
          "468",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7205",
          "02",
          "Águia"
        ],
        [
          "2º",
          "5775",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "4882",
          "21",
          "Touro"
        ],
        [
          "4º",
          "1053",
          "14",
          "Gato"
        ],
        [
          "5º",
          "1914",
          "04",
          "Borboleta"
        ],
        [
          "6º [soma]",
          "0829",
          "",
          ""
        ],
        [
          "7º [mult]",
          "608",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7205",
          "02",
          "Águia"
        ],
        [
          "2º",
          "5775",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "4882",
          "21",
          "Touro"
        ],
        [
          "4º",
          "1053",
          "14",
          "Gato"
        ],
        [
          "5º",
          "1914",
          "04",
          "Borboleta"
        ],
        [
          "6º",
          "7541",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "2780",
          "20",
          "Peru"
        ],
        [
          "8º",
          "0785",
          "22",
          "Tigre"
        ],
        [
          "9º",
          "5523",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "7458",
          "15",
          "Jacaré"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7027",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "9154",
          "14",
          "Gato"
        ],
        [
          "3º",
          "4638",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "9313",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "4657",
          "15",
          "Jacaré"
        ],
        [
          "6º [soma]",
          "4789",
          "",
          ""
        ],
        [
          "7º [mult]",
          "325",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7027",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "9154",
          "14",
          "Gato"
        ],
        [
          "3º",
          "4638",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "9313",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "4657",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "7949",
          "13",
          "Galo"
        ],
        [
          "7º",
          "0163",
          "16",
          "Leão"
        ],
        [
          "8º",
          "2531",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "7483",
          "21",
          "Touro"
        ],
        [
          "10º",
          "2915",
          "04",
          "Borboleta"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7447",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "1689",
          "23",
          "Urso"
        ],
        [
          "3º",
          "6054",
          "14",
          "Gato"
        ],
        [
          "4º",
          "9065",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "0703",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "4958",
          "",
          ""
        ],
        [
          "7º [mult]",
          "577",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7447",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "1689",
          "23",
          "Urso"
        ],
        [
          "3º",
          "6054",
          "14",
          "Gato"
        ],
        [
          "4º",
          "9065",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "0703",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "7169",
          "18",
          "Porco"
        ],
        [
          "7º",
          "4600",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "4856",
          "14",
          "Gato"
        ],
        [
          "9º",
          "7945",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "9528",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8124",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "9503",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "9027",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "3200",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "4051",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "3905",
          "",
          ""
        ],
        [
          "7º [mult]",
          "202",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8124",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "9503",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "9027",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "3200",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "4051",
          "13",
          "Galo"
        ],
        [
          "6º",
          "8993",
          "24",
          "Veado"
        ],
        [
          "7º",
          "1502",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "2020",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "4370",
          "18",
          "Porco"
        ],
        [
          "10º",
          "0790",
          "23",
          "Urso"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6026",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "3150",
          "13",
          "Galo"
        ],
        [
          "3º",
          "0860",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "0696",
          "24",
          "Veado"
        ],
        [
          "5º",
          "1634",
          "09",
          "Cobra"
        ],
        [
          "6º [soma]",
          "2366",
          "",
          ""
        ],
        [
          "7º [mult]",
          "981",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6026",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "3150",
          "13",
          "Galo"
        ],
        [
          "3º",
          "0860",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "0696",
          "24",
          "Veado"
        ],
        [
          "5º",
          "1634",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "6300",
          "25",
          "Vaca"
        ],
        [
          "7º",
          "0186",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "2569",
          "18",
          "Porco"
        ],
        [
          "9º",
          "6006",
          "02",
          "Águia"
        ],
        [
          "10º",
          "7427",
          "07",
          "Carneiro"
        ]
      ]
    }
  ]
};