const resultado = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2064",
          "16",
          "Leão"
        ],
        [
          "2º",
          "8373",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "9287",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "2261",
          "16",
          "Leão"
        ],
        [
          "5º",
          "2803",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "5425",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "6726",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "9598",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "6409",
          "03",
          "Burro"
        ],
        [
          "10º",
          "6265",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9618",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "5080",
          "20",
          "Peru"
        ],
        [
          "3º",
          "3203",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "5229",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "1723",
          "06",
          "Cabra"
        ],
        [
          "6º",
          "5765",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "7902",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "1236",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "7933",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "0348",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6237",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "2349",
          "13",
          "Galo"
        ],
        [
          "3º",
          "5366",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "4673",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "2004",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "1737",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "1195",
          "24",
          "Veado"
        ],
        [
          "8º",
          "8824",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "9434",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "4817",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "19h - MALUCA - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0491",
          "23",
          "Urso"
        ],
        [
          "2º",
          "1351",
          "13",
          "Galo"
        ],
        [
          "3º",
          "7822",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "4219",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "8911",
          "03",
          "Burro"
        ],
        [
          "6º",
          "3119",
          "05",
          "Cachorro"
        ],
        [
          "7º",
          "2593",
          "24",
          "Veado"
        ],
        [
          "8º",
          "3531",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "4084",
          "21",
          "Touro"
        ],
        [
          "10º",
          "2047",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "21h - MALUCA - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6883",
          "21",
          "Touro"
        ],
        [
          "2º",
          "0320",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "7161",
          "16",
          "Leão"
        ],
        [
          "4º",
          "7908",
          "02",
          "Águia"
        ],
        [
          "5º",
          "6229",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "7653",
          "14",
          "Gato"
        ],
        [
          "7º",
          "3027",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "4979",
          "20",
          "Peru"
        ],
        [
          "9º",
          "8113",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "4638",
          "10",
          "Coelho"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2982",
          "21",
          "Touro"
        ],
        [
          "2º",
          "2230",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "6876",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "1734",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "3082",
          "21",
          "Touro"
        ],
        [
          "6º",
          "6965",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "4574",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "0922",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "9865",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "5626",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5359",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "2206",
          "02",
          "Águia"
        ],
        [
          "3º",
          "2081",
          "21",
          "Touro"
        ],
        [
          "4º",
          "9308",
          "02",
          "Águia"
        ],
        [
          "5º",
          "3271",
          "18",
          "Porco"
        ],
        [
          "6º",
          "7175",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "9297",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "3306",
          "02",
          "Águia"
        ],
        [
          "9º",
          "3625",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "8430",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "15h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4526",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "6332",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "7643",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "3697",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "4002",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "9811",
          "03",
          "Burro"
        ],
        [
          "7º",
          "4817",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "3293",
          "24",
          "Veado"
        ],
        [
          "9º",
          "4457",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "7184",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "19h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4710",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2834",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "1259",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "9211",
          "03",
          "Burro"
        ],
        [
          "5º",
          "1198",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "4323",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "0551",
          "13",
          "Galo"
        ],
        [
          "8º",
          "8391",
          "23",
          "Urso"
        ],
        [
          "9º",
          "4139",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "7402",
          "01",
          "Avestruz"
        ]
      ]
    },
    {
      "titulo": "21h - BA - Resultado do dia 17/10/2024 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7706",
          "02",
          "Águia"
        ],
        [
          "2º",
          "9138",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "0628",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "8103",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "9226",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "8437",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "1906",
          "02",
          "Águia"
        ],
        [
          "8º",
          "1725",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "3973",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "8364",
          "16",
          "Leão"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7695",
          "24",
          "Veado"
        ],
        [
          "2º",
          "8435",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "7792",
          "23",
          "Urso"
        ],
        [
          "4º",
          "0148",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "5088",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "7950",
          "13",
          "Galo"
        ],
        [
          "7º",
          "9502",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "9577",
          "20",
          "Peru"
        ],
        [
          "9º",
          "1213",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "4675",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1794",
          "24",
          "Veado"
        ],
        [
          "2º",
          "4067",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "8971",
          "18",
          "Porco"
        ],
        [
          "4º",
          "2817",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "1268",
          "17",
          "Macaco"
        ],
        [
          "6º",
          "3674",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "0916",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "3963",
          "16",
          "Leão"
        ],
        [
          "9º",
          "3874",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "3975",
          "19",
          "Pavão"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 15:45 (tarde II)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9533",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "8925",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "6188",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "0901",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "2393",
          "24",
          "Veado"
        ],
        [
          "6º",
          "1086",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "0302",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "5355",
          "14",
          "Gato"
        ],
        [
          "9º",
          "4996",
          "24",
          "Veado"
        ],
        [
          "10º",
          "1040",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 19:00 (noite)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2632",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "9179",
          "20",
          "Peru"
        ],
        [
          "3º",
          "5701",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "9580",
          "20",
          "Peru"
        ],
        [
          "5º",
          "6036",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "4987",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "5613",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "6617",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "1912",
          "03",
          "Burro"
        ],
        [
          "10º",
          "2655",
          "14",
          "Gato"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9497",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "2377",
          "20",
          "Peru"
        ],
        [
          "3º",
          "8400",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "8365",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "0625",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "9264",
          "",
          ""
        ],
        [
          "7º [mult]",
          "574",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9497",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "2377",
          "20",
          "Peru"
        ],
        [
          "3º",
          "8400",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "8365",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "0625",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "9288",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "4343",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "9706",
          "02",
          "Águia"
        ],
        [
          "9º",
          "7705",
          "02",
          "Águia"
        ],
        [
          "10º",
          "0306",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5861",
          "16",
          "Leão"
        ],
        [
          "2º",
          "2050",
          "13",
          "Galo"
        ],
        [
          "3º",
          "9005",
          "02",
          "Águia"
        ],
        [
          "4º",
          "6324",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "7249",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "0489",
          "",
          ""
        ],
        [
          "7º [mult]",
          "015",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5861",
          "16",
          "Leão"
        ],
        [
          "2º",
          "2050",
          "13",
          "Galo"
        ],
        [
          "3º",
          "9005",
          "02",
          "Águia"
        ],
        [
          "4º",
          "6324",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "7249",
          "13",
          "Galo"
        ],
        [
          "6º",
          "5296",
          "24",
          "Veado"
        ],
        [
          "7º",
          "8003",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "6502",
          "01",
          "Avestruz"
        ],
        [
          "9º",
          "1054",
          "14",
          "Gato"
        ],
        [
          "10º",
          "1344",
          "11",
          "Cavalo"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4307",
          "02",
          "Águia"
        ],
        [
          "2º",
          "6183",
          "21",
          "Touro"
        ],
        [
          "3º",
          "7066",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "7139",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "5950",
          "13",
          "Galo"
        ],
        [
          "6º",
          "4677",
          "20",
          "Peru"
        ],
        [
          "7º",
          "3101",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "0863",
          "16",
          "Leão"
        ],
        [
          "9º",
          "7369",
          "18",
          "Porco"
        ],
        [
          "10º",
          "6655",
          "14",
          "Gato"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0001",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "5928",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "1507",
          "02",
          "Águia"
        ],
        [
          "4º",
          "6479",
          "20",
          "Peru"
        ],
        [
          "5º",
          "7205",
          "02",
          "Águia"
        ],
        [
          "6º [soma]",
          "1120",
          "",
          ""
        ],
        [
          "7º [mult]",
          "005",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0001",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "5928",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "1507",
          "02",
          "Águia"
        ],
        [
          "4º",
          "6479",
          "20",
          "Peru"
        ],
        [
          "5º",
          "7205",
          "02",
          "Águia"
        ],
        [
          "6º",
          "0516",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "0954",
          "14",
          "Gato"
        ],
        [
          "8º",
          "0207",
          "02",
          "Águia"
        ],
        [
          "9º",
          "1879",
          "20",
          "Peru"
        ],
        [
          "10º",
          "4676",
          "19",
          "Pavão"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5080",
          "20",
          "Peru"
        ],
        [
          "2º",
          "8840",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "6101",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "2606",
          "02",
          "Águia"
        ],
        [
          "5º",
          "2038",
          "10",
          "Coelho"
        ],
        [
          "6º [soma]",
          "4665",
          "",
          ""
        ],
        [
          "7º [mult]",
          "907",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5080",
          "20",
          "Peru"
        ],
        [
          "2º",
          "8840",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "6101",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "2606",
          "02",
          "Águia"
        ],
        [
          "5º",
          "2038",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "5862",
          "16",
          "Leão"
        ],
        [
          "7º",
          "0816",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "8400",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "0016",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "9759",
          "15",
          "Jacaré"
        ]
      ]
    }
  ]
};