const resultado = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3667",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "2297",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "1001",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "4895",
          "24",
          "Veado"
        ],
        [
          "5º",
          "0808",
          "02",
          "Águia"
        ],
        [
          "6º",
          "4910",
          "03",
          "Burro"
        ],
        [
          "7º",
          "1260",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "1976",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "3705",
          "02",
          "Águia"
        ],
        [
          "10º",
          "0272",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1150",
          "13",
          "Galo"
        ],
        [
          "2º",
          "8336",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "7071",
          "18",
          "Porco"
        ],
        [
          "4º",
          "3757",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "0948",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "6747",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "3771",
          "18",
          "Porco"
        ],
        [
          "8º",
          "3326",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "0301",
          "01",
          "Avestruz"
        ],
        [
          "10º",
          "9010",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3024",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "1302",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "5625",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "5785",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "1084",
          "21",
          "Touro"
        ],
        [
          "6º",
          "9672",
          "18",
          "Porco"
        ],
        [
          "7º",
          "2128",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "5657",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "5425",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "0258",
          "15",
          "Jacaré"
        ]
      ]
    },
    {
      "titulo": "19h - MALUCA - BA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1184",
          "21",
          "Touro"
        ],
        [
          "2º",
          "7387",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "7092",
          "23",
          "Urso"
        ],
        [
          "4º",
          "0117",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "6598",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "2657",
          "15",
          "Jacaré"
        ],
        [
          "7º",
          "0329",
          "08",
          "Camelo"
        ],
        [
          "8º",
          "8449",
          "13",
          "Galo"
        ],
        [
          "9º",
          "9842",
          "11",
          "Cavalo"
        ],
        [
          "10º",
          "8426",
          "07",
          "Carneiro"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4123",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "8026",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "9096",
          "24",
          "Veado"
        ],
        [
          "4º",
          "5177",
          "20",
          "Peru"
        ],
        [
          "5º",
          "8080",
          "20",
          "Peru"
        ],
        [
          "6º",
          "3114",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "7929",
          "08",
          "Camelo"
        ],
        [
          "8º",
          "0761",
          "16",
          "Leão"
        ],
        [
          "9º",
          "5600",
          "25",
          "Vaca"
        ],
        [
          "10º",
          "2720",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3781",
          "21",
          "Touro"
        ],
        [
          "2º",
          "7031",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "5735",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "7160",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "8490",
          "23",
          "Urso"
        ],
        [
          "6º",
          "0336",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "3377",
          "20",
          "Peru"
        ],
        [
          "8º",
          "0274",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "1617",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "0109",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "15h - BA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5513",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "7630",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "8202",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "5524",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "4801",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "5529",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "4616",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "2527",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "5782",
          "21",
          "Touro"
        ],
        [
          "10º",
          "8520",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "19h - BA - Resultado do dia 14/10/2024 (Segunda-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0771",
          "18",
          "Porco"
        ],
        [
          "2º",
          "1031",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "1988",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "7274",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "8956",
          "14",
          "Gato"
        ],
        [
          "6º",
          "9802",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "8436",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "4425",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "2997",
          "25",
          "Vaca"
        ],
        [
          "10º",
          "6248",
          "12",
          "Elefante"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4089",
          "23",
          "Urso"
        ],
        [
          "2º",
          "1326",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "2257",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "5510",
          "03",
          "Burro"
        ],
        [
          "5º",
          "4179",
          "20",
          "Peru"
        ],
        [
          "6º",
          "0606",
          "02",
          "Águia"
        ],
        [
          "7º",
          "3583",
          "21",
          "Touro"
        ],
        [
          "8º",
          "6879",
          "20",
          "Peru"
        ],
        [
          "9º",
          "1950",
          "13",
          "Galo"
        ],
        [
          "10º",
          "6500",
          "25",
          "Vaca"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3508",
          "02",
          "Águia"
        ],
        [
          "2º",
          "0735",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "7016",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "0119",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "0687",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "4644",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "2692",
          "23",
          "Urso"
        ],
        [
          "8º",
          "7175",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "5407",
          "02",
          "Águia"
        ],
        [
          "10º",
          "6831",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 15:45 (tarde II)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5701",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "5494",
          "24",
          "Veado"
        ],
        [
          "3º",
          "9281",
          "21",
          "Touro"
        ],
        [
          "4º",
          "5879",
          "20",
          "Peru"
        ],
        [
          "5º",
          "0244",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "6809",
          "03",
          "Burro"
        ],
        [
          "7º",
          "5054",
          "14",
          "Gato"
        ],
        [
          "8º",
          "3978",
          "20",
          "Peru"
        ],
        [
          "9º",
          "2429",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "6328",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 19:00 (noite)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6943",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "3452",
          "13",
          "Galo"
        ],
        [
          "3º",
          "5088",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "5866",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "1983",
          "21",
          "Touro"
        ],
        [
          "6º",
          "7175",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "8043",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "3225",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "5632",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "2676",
          "19",
          "Pavão"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9335",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "5855",
          "14",
          "Gato"
        ],
        [
          "3º",
          "5767",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "4645",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "3447",
          "12",
          "Elefante"
        ],
        [
          "6º [soma]",
          "9049",
          "",
          ""
        ],
        [
          "7º [mult]",
          "656",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9335",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "5855",
          "14",
          "Gato"
        ],
        [
          "3º",
          "5767",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "4645",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "3447",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "9554",
          "14",
          "Gato"
        ],
        [
          "7º",
          "3876",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "3564",
          "16",
          "Leão"
        ],
        [
          "9º",
          "5575",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "1618",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7210",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2149",
          "13",
          "Galo"
        ],
        [
          "3º",
          "4902",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "7654",
          "14",
          "Gato"
        ],
        [
          "5º",
          "4908",
          "02",
          "Águia"
        ],
        [
          "6º [soma]",
          "6823",
          "",
          ""
        ],
        [
          "7º [mult]",
          "494",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7210",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2149",
          "13",
          "Galo"
        ],
        [
          "3º",
          "4902",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "7654",
          "14",
          "Gato"
        ],
        [
          "5º",
          "4908",
          "02",
          "Águia"
        ],
        [
          "6º",
          "7247",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "2196",
          "24",
          "Veado"
        ],
        [
          "8º",
          "1405",
          "02",
          "Águia"
        ],
        [
          "9º",
          "0924",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "8595",
          "24",
          "Veado"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3338",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "7971",
          "18",
          "Porco"
        ],
        [
          "3º",
          "1914",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "6656",
          "14",
          "Gato"
        ],
        [
          "5º",
          "5989",
          "23",
          "Urso"
        ],
        [
          "6º [soma]",
          "5868",
          "",
          ""
        ],
        [
          "7º [mult]",
          "607",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3338",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "7971",
          "18",
          "Porco"
        ],
        [
          "3º",
          "1914",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "6656",
          "14",
          "Gato"
        ],
        [
          "5º",
          "5989",
          "23",
          "Urso"
        ],
        [
          "6º",
          "3716",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "3996",
          "24",
          "Veado"
        ],
        [
          "8º",
          "3715",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "8146",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "5441",
          "11",
          "Cavalo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4059",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "2698",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "4894",
          "24",
          "Veado"
        ],
        [
          "4º",
          "3919",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "3072",
          "18",
          "Porco"
        ],
        [
          "6º [soma]",
          "8642",
          "",
          ""
        ],
        [
          "7º [mult]",
          "951",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4059",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "2698",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "4894",
          "24",
          "Veado"
        ],
        [
          "4º",
          "3919",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "3072",
          "18",
          "Porco"
        ],
        [
          "6º",
          "4243",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "0689",
          "23",
          "Urso"
        ],
        [
          "8º",
          "5991",
          "23",
          "Urso"
        ],
        [
          "9º",
          "9849",
          "13",
          "Galo"
        ],
        [
          "10º",
          "9414",
          "04",
          "Borboleta"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3691",
          "23",
          "Urso"
        ],
        [
          "2º",
          "3874",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "4251",
          "13",
          "Galo"
        ],
        [
          "4º",
          "1857",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "1109",
          "03",
          "Burro"
        ],
        [
          "6º [soma]",
          "4782",
          "",
          ""
        ],
        [
          "7º [mult]",
          "298",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3691",
          "23",
          "Urso"
        ],
        [
          "2º",
          "3874",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "4251",
          "13",
          "Galo"
        ],
        [
          "4º",
          "1857",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "1109",
          "03",
          "Burro"
        ],
        [
          "6º",
          "3341",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "6828",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "9755",
          "14",
          "Gato"
        ],
        [
          "9º",
          "1417",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "6123",
          "06",
          "Cabra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3199",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "3160",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "9263",
          "16",
          "Leão"
        ],
        [
          "4º",
          "2519",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "8722",
          "06",
          "Cabra"
        ],
        [
          "6º [soma]",
          "6863",
          "",
          ""
        ],
        [
          "7º [mult]",
          "108",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3199",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "3160",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "9263",
          "16",
          "Leão"
        ],
        [
          "4º",
          "2519",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "8722",
          "06",
          "Cabra"
        ],
        [
          "6º",
          "3392",
          "23",
          "Urso"
        ],
        [
          "7º",
          "1125",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "9661",
          "16",
          "Leão"
        ],
        [
          "9º",
          "9039",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "0080",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 21h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1927",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "0305",
          "02",
          "Águia"
        ],
        [
          "3º",
          "3691",
          "23",
          "Urso"
        ],
        [
          "4º",
          "6891",
          "23",
          "Urso"
        ],
        [
          "5º",
          "3663",
          "16",
          "Leão"
        ],
        [
          "6º [soma]",
          "6477",
          "",
          ""
        ],
        [
          "7º [mult]",
          "587",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 21h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1927",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "0305",
          "02",
          "Águia"
        ],
        [
          "3º",
          "3691",
          "23",
          "Urso"
        ],
        [
          "4º",
          "6891",
          "23",
          "Urso"
        ],
        [
          "5º",
          "3663",
          "16",
          "Leão"
        ],
        [
          "6º",
          "1036",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "9368",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "2099",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "7511",
          "03",
          "Burro"
        ],
        [
          "10º",
          "6491",
          "23",
          "Urso"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7902",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "1719",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "9785",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "5262",
          "16",
          "Leão"
        ],
        [
          "5º",
          "0536",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "7195",
          "24",
          "Veado"
        ],
        [
          "7º",
          "9772",
          "18",
          "Porco"
        ],
        [
          "8º",
          "0186",
          "22",
          "Tigre"
        ],
        [
          "9º",
          "2952",
          "13",
          "Galo"
        ],
        [
          "10º",
          "5309",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6243",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "5439",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "8758",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "6597",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "1481",
          "21",
          "Touro"
        ],
        [
          "6º",
          "6586",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "2475",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "4359",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "3987",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "5925",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0454",
          "14",
          "Gato"
        ],
        [
          "2º",
          "8647",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "0193",
          "24",
          "Veado"
        ],
        [
          "4º",
          "7660",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "4667",
          "17",
          "Macaco"
        ],
        [
          "6º",
          "0807",
          "02",
          "Águia"
        ],
        [
          "7º",
          "4616",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "5496",
          "24",
          "Veado"
        ],
        [
          "9º",
          "4730",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "7270",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 15:45h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1075",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "2467",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "7520",
          "05",
          "Cachorro"
        ],
        [
          "4º",
          "7615",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "0329",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "1277",
          "20",
          "Peru"
        ],
        [
          "7º",
          "0456",
          "14",
          "Gato"
        ],
        [
          "8º",
          "7621",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "5705",
          "02",
          "Águia"
        ],
        [
          "10º",
          "4065",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 18h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2735",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "5809",
          "03",
          "Burro"
        ],
        [
          "3º",
          "4988",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "4319",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "3937",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "2544",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "7893",
          "24",
          "Veado"
        ],
        [
          "8º",
          "3081",
          "21",
          "Touro"
        ],
        [
          "9º",
          "5989",
          "23",
          "Urso"
        ],
        [
          "10º",
          "1295",
          "24",
          "Veado"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 20:00",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8492",
          "23",
          "Urso"
        ],
        [
          "2º",
          "3452",
          "13",
          "Galo"
        ],
        [
          "3º",
          "6613",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "2268",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "8484",
          "21",
          "Touro"
        ],
        [
          "6º",
          "8362",
          "16",
          "Leão"
        ],
        [
          "7º",
          "4462",
          "16",
          "Leão"
        ],
        [
          "8º",
          "9516",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "2238",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "3887",
          "22",
          "Tigre"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9265",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "5819",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "4636",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "1528",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "6011",
          "03",
          "Burro"
        ],
        [
          "6º [soma]",
          "7259",
          "",
          ""
        ],
        [
          "7º [mult]",
          "913",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9265",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "5819",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "4636",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "1528",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "6011",
          "03",
          "Burro"
        ],
        [
          "6º",
          "9541",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "2865",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "6132",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "5968",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "1765",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3586",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "0055",
          "14",
          "Gato"
        ],
        [
          "3º",
          "0511",
          "03",
          "Burro"
        ],
        [
          "4º",
          "1602",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "6351",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "2105",
          "",
          ""
        ],
        [
          "7º [mult]",
          "197",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3586",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "0055",
          "14",
          "Gato"
        ],
        [
          "3º",
          "0511",
          "03",
          "Burro"
        ],
        [
          "4º",
          "1602",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "6351",
          "13",
          "Galo"
        ],
        [
          "6º",
          "3001",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "5056",
          "14",
          "Gato"
        ],
        [
          "8º",
          "8510",
          "03",
          "Burro"
        ],
        [
          "9º",
          "6512",
          "03",
          "Burro"
        ],
        [
          "10º",
          "5184",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4047",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "5218",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "4048",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "8646",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "7015",
          "04",
          "Borboleta"
        ],
        [
          "6º [soma]",
          "8974",
          "",
          ""
        ],
        [
          "7º [mult]",
          "117",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4047",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "5218",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "4048",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "8646",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "7015",
          "04",
          "Borboleta"
        ],
        [
          "6º",
          "4548",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "0206",
          "02",
          "Águia"
        ],
        [
          "8º",
          "4144",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "7886",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "5758",
          "15",
          "Jacaré"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5438",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "1685",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "5286",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "1742",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4928",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "9079",
          "",
          ""
        ],
        [
          "7º [mult]",
          "163",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5438",
          "10",
          "Coelho"
        ],
        [
          "2º",
          "1685",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "5286",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "1742",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4928",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "5151",
          "13",
          "Galo"
        ],
        [
          "7º",
          "4627",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "3884",
          "21",
          "Touro"
        ],
        [
          "9º",
          "8562",
          "16",
          "Leão"
        ],
        [
          "10º",
          "1303",
          "01",
          "Avestruz"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0021",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "8858",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "8755",
          "14",
          "Gato"
        ],
        [
          "4º",
          "0317",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "6960",
          "15",
          "Jacaré"
        ],
        [
          "6º [soma]",
          "4911",
          "",
          ""
        ],
        [
          "7º [mult]",
          "186",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 18:20, PTN, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0021",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "8858",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "8755",
          "14",
          "Gato"
        ],
        [
          "4º",
          "0317",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "6960",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "0880",
          "20",
          "Peru"
        ],
        [
          "7º",
          "0873",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "2551",
          "13",
          "Galo"
        ],
        [
          "9º",
          "1857",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "1072",
          "18",
          "Porco"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1001",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "8026",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "4147",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "4093",
          "24",
          "Veado"
        ],
        [
          "5º",
          "8375",
          "19",
          "Pavão"
        ],
        [
          "6º [soma]",
          "5642",
          "",
          ""
        ],
        [
          "7º [mult]",
          "034",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1001",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "8026",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "4147",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "4093",
          "24",
          "Veado"
        ],
        [
          "5º",
          "8375",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "1844",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "0010",
          "03",
          "Burro"
        ],
        [
          "8º",
          "0249",
          "13",
          "Galo"
        ],
        [
          "9º",
          "1673",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "9418",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8995",
          "24",
          "Veado"
        ],
        [
          "2º",
          "2485",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "7743",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "4336",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "4165",
          "17",
          "Macaco"
        ],
        [
          "6º [soma]",
          "7724",
          "",
          ""
        ],
        [
          "7º [mult]",
          "352",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8995",
          "24",
          "Veado"
        ],
        [
          "2º",
          "2485",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "7743",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "4336",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "4165",
          "17",
          "Macaco"
        ],
        [
          "6º",
          "8274",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "9473",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "9843",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "5536",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "0850",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 12:00 - PTSP",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2406",
          "02",
          "Águia"
        ],
        [
          "2º",
          "8000",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "3986",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "5961",
          "16",
          "Leão"
        ],
        [
          "5º",
          "3551",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "3904",
          "",
          ""
        ],
        [
          "7º [mult]",
          "248",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8495",
          "24",
          "Veado"
        ],
        [
          "2º",
          "6043",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "6341",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "9369",
          "18",
          "Porco"
        ],
        [
          "5º",
          "1184",
          "21",
          "Touro"
        ],
        [
          "6º [soma]",
          "1432",
          "",
          ""
        ],
        [
          "7º [mult]",
          "335",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8495",
          "24",
          "Veado"
        ],
        [
          "2º",
          "6043",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "6341",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "9369",
          "18",
          "Porco"
        ],
        [
          "5º",
          "1184",
          "21",
          "Touro"
        ],
        [
          "6º",
          "8669",
          "18",
          "Porco"
        ],
        [
          "7º",
          "4033",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "9446",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "5319",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "8899",
          "25",
          "Vaca"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5210",
          "03",
          "Burro"
        ],
        [
          "2º",
          "8001",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "4779",
          "20",
          "Peru"
        ],
        [
          "4º",
          "1777",
          "20",
          "Peru"
        ],
        [
          "5º",
          "4431",
          "08",
          "Camelo"
        ],
        [
          "6º [soma]",
          "4198",
          "",
          ""
        ],
        [
          "7º [mult]",
          "685",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5210",
          "03",
          "Burro"
        ],
        [
          "2º",
          "8001",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "4779",
          "20",
          "Peru"
        ],
        [
          "4º",
          "1777",
          "20",
          "Peru"
        ],
        [
          "5º",
          "4431",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "5841",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "2077",
          "20",
          "Peru"
        ],
        [
          "8º",
          "1077",
          "20",
          "Peru"
        ],
        [
          "9º",
          "0197",
          "25",
          "Vaca"
        ],
        [
          "10º",
          "3390",
          "23",
          "Urso"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0069",
          "18",
          "Porco"
        ],
        [
          "2º",
          "5456",
          "14",
          "Gato"
        ],
        [
          "3º",
          "6849",
          "13",
          "Galo"
        ],
        [
          "4º",
          "7661",
          "16",
          "Leão"
        ],
        [
          "5º",
          "2662",
          "16",
          "Leão"
        ],
        [
          "6º [soma]",
          "2697",
          "",
          ""
        ],
        [
          "7º [mult]",
          "376",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0069",
          "18",
          "Porco"
        ],
        [
          "2º",
          "5456",
          "14",
          "Gato"
        ],
        [
          "3º",
          "6849",
          "13",
          "Galo"
        ],
        [
          "4º",
          "7661",
          "16",
          "Leão"
        ],
        [
          "5º",
          "2662",
          "16",
          "Leão"
        ],
        [
          "6º",
          "0567",
          "17",
          "Macaco"
        ],
        [
          "7º",
          "0486",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "6546",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "9691",
          "23",
          "Urso"
        ],
        [
          "10º",
          "9987",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1528",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "8557",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "0487",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "8905",
          "02",
          "Águia"
        ],
        [
          "5º",
          "8144",
          "11",
          "Cavalo"
        ],
        [
          "6º [soma]",
          "7621",
          "",
          ""
        ],
        [
          "7º [mult]",
          "075",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 19hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1528",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "8557",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "0487",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "8905",
          "02",
          "Águia"
        ],
        [
          "5º",
          "8144",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "1808",
          "02",
          "Águia"
        ],
        [
          "7º",
          "5549",
          "13",
          "Galo"
        ],
        [
          "8º",
          "2580",
          "20",
          "Peru"
        ],
        [
          "9º",
          "8775",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "6333",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6648",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "4843",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "7429",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "4372",
          "18",
          "Porco"
        ],
        [
          "5º",
          "1896",
          "24",
          "Veado"
        ],
        [
          "6º [soma]",
          "5188",
          "",
          ""
        ],
        [
          "7º [mult]",
          "196",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 20hs - PTN SP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6648",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "4843",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "7429",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "4372",
          "18",
          "Porco"
        ],
        [
          "5º",
          "1896",
          "24",
          "Veado"
        ],
        [
          "6º",
          "6474",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "6843",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "4427",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "8392",
          "23",
          "Urso"
        ],
        [
          "10º",
          "1324",
          "06",
          "Cabra"
        ]
      ]
    }
  ]
};